# -*- mode: makefile -*-
##=====================================================================
## OpenGLCppWrapper: A C++11 OpenGL 'Core' wrapper.
## Copyright 2019 Quentin Quadrat <lecrapouille@gmail.com>
##
## This file is part of OpenGLCppWrapper.
##
## OpenGLCppWrapper is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with OpenGLCppWrapper.  If not, see <http://www.gnu.org/licenses/>.
##=====================================================================

###################################################
# OpenGL: glfw and glew libraries
#
ifeq ($(OS),Darwin)
INCLUDES += /usr/local/include /opt/local/include
LINKER_FLAGS += -framework OpenGL -framework Cocoa
LINKER_FLAGS += -framework IOKit -framework CoreVideo
LINKER_FLAGS += -L/usr/local/lib -L/opt/local/lib
LINKER_FLAGS += -lGLEW -lglfw
else ifeq ($(OS),Linux)
PKG_LIBS += glew --static glfw3
else
$(error Unknown architecture)
endif

###################################################
# SOIL (image loader for OpenGL texturing)
#
THIRD_PARTIES_LIBS += $(abspath $(THIRD_PARTIES_DIR)/SOIL/build/libSOIL.a)
INCLUDES += $(THIRD_PARTIES_DIR)/SOIL/include
VPATH += $(THIRD_PARTIES_DIR)/SOIL/src

###################################################
# Dear IM Gui (immediate mode rendering GUI)
#
THIRD_PARTIES_DIR_OBJS += imgui.o imgui_draw.o imgui_tables.o imgui_widgets.o
THIRD_PARTIES_DIR_OBJS += imgui_impl_glfw.o imgui_impl_opengl3.o
INCLUDES += $(THIRD_PARTIES_DIR)/imgui
VPATH += $(THIRD_PARTIES_DIR)/imgui $(THIRD_PARTIES_DIR)/imgui/backends

# FIXME: temporary
DEFINES += -Wno-old-style-cast -Wno-conversion -Wno-float-equal -Wno-sign-conversion -Wno-cast-qual

###################################################
# Bullet3 (3d physics)
#
THIRD_PARTIES_LIBS += $(abspath $(THIRD_PARTIES_DIR)/bullet3/usr/local/lib/libBulletSoftBody.a)
THIRD_PARTIES_LIBS += $(abspath $(THIRD_PARTIES_DIR)/bullet3/usr/local/lib/libBulletDynamics.a)
THIRD_PARTIES_LIBS += $(abspath $(THIRD_PARTIES_DIR)/bullet3/usr/local/lib/libBulletCollision.a)
THIRD_PARTIES_LIBS += $(abspath $(THIRD_PARTIES_DIR)/bullet3/usr/local/lib/libLinearMath.a)
INCLUDES += $(THIRD_PARTIES_DIR)/bullet3/usr/local/include
INCLUDES += $(THIRD_PARTIES_DIR)/bullet3/usr/local/include/bullet

###################################################
# Units library
#
INCLUDES += $(THIRD_PARTIES_DIR)/units/include

###################################################
# JSON parser
#
INCLUDES += $(THIRD_PARTIES_DIR)/json/include

###################################################
# OpenGLCppWrapper defines.
#
# CHECK_OPENGL allows to check if bad parameters are
#   passed to OpenGL routines. Produce an error message
#   in the console but does not abort the program.
# ENABLE_DEBUG activate logs on the console.

DEFINES += -DCHECK_OPENGL -UENABLE_DEBUG

###################################################
# Inform Makefile where to find header files for third parts
#
INCLUDES += $(P)/include $(P)/src $(P)/src/Loaders/3D
INCLUDES += $(THIRD_PARTIES_DIR)

###################################################
# Inform Makefile where to find *.cpp and *.o files
#
VPATH += $(P)/src $(P)/src/Common $(P)/src/Math
VPATH += $(P)/src/OpenGL $(P)/src/OpenGL/Buffers
VPATH += $(P)/src/OpenGL/Context $(P)/src/OpenGL/Shaders
VPATH += $(P)/src/OpenGL/Textures $(P)/src/OpenGL/Variables
VPATH += $(P)/src/UI $(P)/src/Loaders/Textures $(P)/src/Loaders/3D
VPATH += $(P)/src/Components $(P)/src/Components/Physics
VPATH += $(P)/src/Scene/Material $(P)/src/Scene/Geometry $(P)/src/Scene
VPATH += $(P)/src/Scene/Camera
VPATH += $(THIRD_PARTIES_DIR)

###################################################
# Compiled objects files
#
LIB_FILES += $(call rwildcard,$(P)/src/Common,*.cpp)
LIB_FILES += $(call rwildcard,$(P)/src/Components,*.cpp)
LIB_FILES += $(call rwildcard,$(P)/src/Loaders,*.cpp)
LIB_FILES += $(call rwildcard,$(P)/src/Math,*.cpp)
LIB_FILES += $(call rwildcard,$(P)/src/OpenGL,*.cpp)
LIB_FILES += $(call rwildcard,$(P)/src/Scene,*.cpp)
LIB_FILES += $(call rwildcard,$(P)/src/UI,*.cpp)